# Generated by Django 5.2.3 on 2025-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
