# Generated by Django 5.2.3 on 2025-12-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(default='لايوجد', max_length=15),
            preserve_default=False,
        ),
    ]
