# Generated by Django 5.2.3 on 2025-12-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_users_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير'), ('employee', 'موظف'), ('designer', 'Designer')], default='employee', max_length=10),
        ),
    ]
