# Generated by Django 4.2 on 2026-03-10 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_type_U_N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='(تحديث ام جديد)نوع المقال')),
                ('number_of_article', models.PositiveIntegerField(verbose_name='عدد المقالات المسموح بها')),
            ],
        ),
        migrations.CreateModel(
            name='Article_type_W_R_A_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='(تحذير / تقييم/تعليمي/افضل شركات)نوع المقال')),
                ('number_of_article', models.PositiveIntegerField(verbose_name='عدد المقالات المسموح بها')),
            ],
        ),
        migrations.CreateModel(
            name='Category_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='قسم المنيو')),
            ],
        ),
        migrations.CreateModel(
            name='Colors_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='الالوان المتاحة للمنتج')),
            ],
        ),
        migrations.CreateModel(
            name='contract_duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100, verbose_name='مدة العقد')),
                ('number_of_duration', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='رقم مدة العقد بالسنوات')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='اصناف المخزن ')),
            ],
        ),
        migrations.CreateModel(
            name='Official_holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_day', models.IntegerField(choices=[(5, 'السبت')], default=5, verbose_name='اليوم الرسمي للإجازة')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_status_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='حالة ايجار المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموقع')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('number_of_days', models.PositiveIntegerField(verbose_name='عدد ايام الفارق')),
                ('site_link', models.URLField(verbose_name='رابط الموقع')),
                ('sitemaps_links', models.URLField(help_text='ضع كل رابط في سطر جديد', verbose_name='روابط الـ sitemap')),
            ],
        ),
        migrations.CreateModel(
            name='Size_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='احجام المنتجات')),
            ],
        ),
        migrations.CreateModel(
            name='Status_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='حالة الطلب')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100, verbose_name='وحدات التخزين')),
            ],
        ),
        migrations.CreateModel(
            name='CustomHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الإجازة')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب الإجازة (اختياري)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إجازة مخصصة',
                'verbose_name_plural': 'إجازات مخصصة',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
