# Generated by Django 5.2.3 on 2025-06-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='number_of_days',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
