# Generated by Django 5.2.3 on 2025-06-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_site_number_of_days_alter_site_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='number_of_days',
            field=models.PositiveIntegerField(),
        ),
    ]
