# Generated by Django 5.2.3 on 2025-06-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_site_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='site',
            name='number_of_days',
            field=models.PositiveIntegerField(verbose_name='عدد ايام الفارق'),
        ),
        migrations.AlterField(
            model_name='site',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
    ]
