# Generated by Django 5.2.3 on 2025-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_site_name_alter_site_number_of_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_type_U_N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='(تحديث ام جديد)نوع المقال')),
                ('number_of_article', models.PositiveIntegerField(verbose_name='عدد المقالات المسموح بها')),
            ],
        ),
        migrations.CreateModel(
            name='Article_type_W_R_A_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='( تحذير / تقييم/تعليمي/افضل شركات)نوع المقال')),
                ('number_of_article', models.PositiveIntegerField(verbose_name='عدد المقالات المسموح بها')),
            ],
        ),
    ]
