# Generated by Django 5.2.3 on 2025-06-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_article_type_u_n_article_type_w_r_a_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_type_w_r_a_b',
            name='number_of_article',
        ),
    ]
