# Generated by Django 5.2.3 on 2025-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_remove_article_type_w_r_a_b_number_of_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_type_w_r_a_b',
            name='number_of_article',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد المقالات المسموح بها'),
            preserve_default=False,
        ),
    ]
