# Generated by Django 5.2.3 on 2025-07-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_official_holiday_customholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_type_u_n',
            name='max_per_day',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى يومياً'),
        ),
        migrations.AddField(
            model_name='article_type_w_r_a_b',
            name='max_per_day',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى يومياً'),
        ),
        migrations.AlterField(
            model_name='article_type_w_r_a_b',
            name='type',
            field=models.CharField(max_length=100, verbose_name='(تحذير / تقييم/تعليمي/افضل شركات)نوع المقال'),
        ),
        migrations.AlterField(
            model_name='official_holiday',
            name='holiday_day',
            field=models.IntegerField(choices=[(5, 'السبت')], default=5, verbose_name='اليوم الرسمي للإجازة'),
        ),
    ]
