# Generated by Django 5.2.3 on 2025-07-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_article_type_u_n_max_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_type_u_n',
            name='max_per_day',
        ),
        migrations.RemoveField(
            model_name='article_type_w_r_a_b',
            name='max_per_day',
        ),
    ]
