# Generated by Django 5.2.3 on 2025-07-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_remove_article_type_u_n_max_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_link',
            field=models.URLField(default='https://example.com', verbose_name='رابط الموقع'),
            preserve_default=False,
        ),
    ]
