# Generated by Django 5.2.3 on 2025-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_site_site_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='تفاصيل العقد')),
            ],
        ),
    ]
