# Generated by Django 5.2.3 on 2025-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_contract_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_details',
            name='details',
            field=models.CharField(verbose_name='تفاصيل العقد'),
        ),
    ]
