# Generated by Django 5.2.3 on 2025-12-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_alter_contract_details_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract_duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100, verbose_name='مدة العقد')),
                ('number_of_duration', models.PositiveIntegerField(verbose_name='رقم مدة العقد بالسنوات')),
            ],
        ),
    ]
