# Generated by Django 5.2.3 on 2025-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_contract_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_duration',
            name='number_of_duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='رقم مدة العقد بالسنوات'),
        ),
    ]
