# Generated by Django 5.2.3 on 2025-12-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_alter_contract_duration_number_of_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='sitemaps_links',
            field=models.TextField(default=0, help_text='ضع كل رابط في سطر جديد', verbose_name='روابط الـ sitemap'),
            preserve_default=False,
        ),
    ]
