# Generated by Django 5.2.3 on 2025-12-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_site_sitemaps_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='sitemaps_links',
            field=models.URLField(help_text='ضع كل رابط في سطر جديد', verbose_name='روابط الـ sitemap'),
        ),
    ]
