# Generated by Django 5.2.3 on 2025-12-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_alter_site_sitemaps_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='قسم المنيو')),
            ],
        ),
    ]
