# Generated by Django 5.2.3 on 2026-01-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0018_category_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='حالة الطلب')),
            ],
        ),
    ]
