# Generated by Django 5.2.3 on 2026-01-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0019_status_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='اصناف المخزن ')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100, verbose_name='وحدات التخزين')),
            ],
        ),
    ]
