# Generated by Django 6.0.1 on 2026-01-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0020_ingredientcategory_unit_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='الالوان المتاحة للمنتج')),
            ],
        ),
        migrations.CreateModel(
            name='Size_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='احجام المنتجات')),
            ],
        ),
    ]
