# Generated by Django 6.0.1 on 2026-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_colors_choices_size_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_status_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='حالة ايجار المنتج')),
            ],
        ),
    ]
