# Generated by Django 4.2 on 2026-01-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0022_rental_status_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contract_details',
        ),
    ]
