# Generated by Django 4.2 on 2026-03-10 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='اسم العميل')),
                ('mobil', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=1000, verbose_name='عنوان العميل')),
                ('number_of_orders', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية الحالية')),
                ('min_limit', models.PositiveIntegerField(verbose_name='حد الطلب (الحد الأدنى)')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('supply_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة التوريد')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الربح المتوقع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_rental', models.BooleanField(default=False, verbose_name='هل الصنف للإيجار؟')),
                ('rental_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='كود الصنف')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('visa', 'Visa')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.customer', verbose_name='العميل')),
                ('status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.status_order', verbose_name='حالة الطلب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(editable=False, max_length=50, unique=True, verbose_name='كود البدلة')),
                ('rental_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الإيجار')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الربح من الإيجار')),
                ('item', models.ForeignKey(limit_choices_to={'is_rental': True}, on_delete=django.db.models.deletion.CASCADE, to='pos.inventoryitem', verbose_name='البدلة')),
                ('status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.rental_status_choices', verbose_name='حالة البدلة')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='اسم المورد')),
                ('mobil', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=1000, verbose_name='عنوان المورد')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='التصنيف')),
                ('number_of_supplies', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية المضافة')),
                ('cost_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الوحدة عند الشراء')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي قيمة الطلبية')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المتبقي (دين)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوريد')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.inventoryitem', verbose_name='الصنف المورد')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_history', to='pos.supplier', verbose_name='المورد')),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='تاريخ الحجز / الخروج')),
                ('return_date', models.DateField(verbose_name='تاريخ العودة المتوقع')),
                ('pants_size', models.CharField(max_length=50, verbose_name='مقاس البنطلون')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة الفعلي')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الإيجار')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ التأمين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات (مقاسات، تعديلات)')),
                ('late_damage_penalty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='غرامة التأخير أو التلف')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.colors_choices', verbose_name='اللون')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer', verbose_name='العميل')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.rentalitem', verbose_name='البدلة')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.size_choices', verbose_name='المقاس')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.rental_status_choices', verbose_name='حالة البدلة')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('available', models.BooleanField(default=True, verbose_name='متاح')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category_products', verbose_name='التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.inventoryitem', verbose_name='الصنف')),
                ('rental_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.rentalorder', verbose_name='طلب إيجار')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='categories.ingredientcategory', verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.colors_choices', verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.size_choices', verbose_name='الحجم'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.unit_choices', verbose_name='الوحدة'),
        ),
    ]
