# Generated by Django 6.0.1 on 2026-01-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_colors_choices_size_choices'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='اسم المورد')),
                ('mobil', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=1000, verbose_name='عنوان المورد')),
                ('number_of_supplies', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.colors_choices', verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الربح المتوقع'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.size_choices', verbose_name='الحجم'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplyـcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة التوريد'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.supplier', verbose_name='المورد'),
        ),
    ]
