# Generated by Django 6.0.1 on 2026-01-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_supplier_inventoryitem_color_inventoryitem_profit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='supplyـcost',
            new_name='supply_cost',
        ),
    ]
