# Generated by Django 6.0.1 on 2026-01-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_rename_supplyـcost_inventoryitem_supply_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المضافة')),
                ('cost_at_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة عند الشراء')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي المدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوريد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.inventoryitem', verbose_name='الصنف المورد')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_history', to='pos.supplier', verbose_name='المورد')),
            ],
        ),
    ]
