# Generated by Django 5.2.3 on 2026-01-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_supplylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplylog',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع حالياً'),
        ),
        migrations.AddField(
            model_name='supplylog',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المتبقي (دين)'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي قيمة الطلبية'),
        ),
    ]
