# Generated by Django 5.2.3 on 2026-01-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_supplylog_paid_amount_supplylog_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='cost_at_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الوحدة عند الشراء'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.inventoryitem', verbose_name='الصنف المورد'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='quantity_added',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية المضافة'),
        ),
        migrations.AlterField(
            model_name='supplylog',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي قيمة الطلبية'),
        ),
    ]
