# Generated by Django 6.0.1 on 2026-01-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_orderitem_price_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح حالياً (غير محجوز)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_for_rental',
            field=models.BooleanField(default=False, verbose_name='متاح للإيجار؟'),
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='تاريخ الحجز/الخروج')),
                ('return_date', models.DateField(verbose_name='تاريخ العودة المتوقع')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة الفعلي')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الإيجار')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ التأمين')),
                ('status', models.CharField(choices=[('booked', 'محجوز'), ('picked_up', 'تم الاستلام'), ('returned', 'تم الترجيع'), ('late', 'متأخر')], default='booked', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات (مقاسات، تعديلات)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer', verbose_name='العميل')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.inventoryitem', verbose_name='البدلة')),
            ],
        ),
    ]
