# Generated by Django 5.2.3 on 2026-01-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_inventoryitem_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_for_rental',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rental_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.rentalorder', verbose_name='طلب إيجار'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.order', verbose_name='رقم الفاتورة'),
        ),
    ]
