# Generated by Django 5.2.3 on 2026-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_remove_inventoryitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الربح من الإيجار'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='total_rentals',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي مرات الإيجار'),
        ),
    ]
