# Generated by Django 6.0.1 on 2026-01-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_colors_choices_size_choices'),
        ('pos', '0010_rentalorder_total_profit_rentalorder_total_rentals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='total_rentals',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_rental',
            field=models.BooleanField(default=False, verbose_name='هل الصنف للإيجار؟'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='rental_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='كود الصنف'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الربح من الإيجار'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_rentals',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي مرات الإيجار'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='Supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.supplier', verbose_name='المورد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='color',
            field=models.ForeignKey(default=5465, on_delete=django.db.models.deletion.CASCADE, to='categories.colors_choices', verbose_name='اللون'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='min_limit',
            field=models.PositiveIntegerField(verbose_name='حد الطلب (الحد الأدنى)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الربح المتوقع'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية الحالية'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='size',
            field=models.ForeignKey(default=66656, on_delete=django.db.models.deletion.CASCADE, to='categories.size_choices', verbose_name='الحجم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supply_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة التوريد'),
        ),
    ]
