# Generated by Django 6.0.1 on 2026-01-23 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0022_rental_status_choices'),
        ('pos', '0011_remove_rentalorder_total_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(editable=False, max_length=50, unique=True, verbose_name='كود البدلة')),
                ('rental_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الإيجار')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الربح من الإيجار')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.inventoryitem', verbose_name='البدلة')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.rental_status_choices', verbose_name='حالة البدلة')),
            ],
        ),
    ]
