# Generated by Django 6.0.1 on 2026-01-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0022_rental_status_choices'),
        ('pos', '0012_rentalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.rental_status_choices', verbose_name='حالة البدلة'),
        ),
    ]
