# Generated by Django 6.0.1 on 2026-01-23 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_rentalitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.rentalitem', verbose_name='البدلة'),
        ),
    ]
