# Generated by Django 6.0.1 on 2026-01-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_alter_rentalorder_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='item',
            field=models.ForeignKey(limit_choices_to={'is_rental': True}, on_delete=django.db.models.deletion.CASCADE, to='pos.inventoryitem', verbose_name='البدلة'),
        ),
    ]
