# Generated by Django 6.0.1 on 2026-01-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_alter_rentalitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='order',
        ),
    ]
