# Generated by Django 6.0.1 on 2026-01-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_remove_rentalorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='total_rentals',
        ),
    ]
