# Generated by Django 6.0.1 on 2026-01-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0022_rental_status_choices'),
        ('pos', '0019_remove_inventoryitem_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='color',
            field=models.ForeignKey(default=7678, on_delete=django.db.models.deletion.CASCADE, to='categories.colors_choices', verbose_name='اللون'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='size',
            field=models.ForeignKey(default=767, on_delete=django.db.models.deletion.CASCADE, to='categories.size_choices', verbose_name='المقاس'),
            preserve_default=False,
        ),
    ]
