# Generated by Django 6.0.1 on 2026-01-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_rentalorder_color_rentalorder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='pantsـsize',
            field=models.CharField(default=12, max_length=50, verbose_name='مقاس البنطلون'),
            preserve_default=False,
        ),
    ]
