# Generated by Django 5.2.3 on 2026-01-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0022_rental_status_choices'),
        ('pos', '0021_rentalorder_pantsـsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalorder',
            old_name='pantsـsize',
            new_name='pants_size',
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='rental_date',
            field=models.DateField(verbose_name='تاريخ الحجز / الخروج'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.rental_status_choices', verbose_name='حالة البدلة'),
        ),
    ]
