# Generated by Django 5.2.3 on 2026-01-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_rename_pantsـsize_rentalorder_pants_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='late_damage_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='غرامة التأخير أو التلف'),
        ),
    ]
