# Generated by Django 5.2.3 on 2026-02-07 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0023_delete_contract_details'),
        ('pos', '0023_rentalorder_late_damage_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='min_limit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='rental_code',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supply_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة التوريد (للقطعة)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع المقترح'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية الحالية')),
                ('min_limit', models.PositiveIntegerField(default=5, verbose_name='حد الطلب')),
                ('rental_code', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.colors_choices', verbose_name='اللون')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pos.inventoryitem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.size_choices', verbose_name='المقاس')),
            ],
        ),
    ]
